baseURL = 'https://emad.blog/'
languageCode = 'en-us'
title = "Emad's Blog"
theme = 'hugo-PaperMod'


[params]
  # Load custom CSS that includes @font-face for Font Awesome
    customCSS = ["css/custom.css", "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"]




  enableStaticFileDeploy = true

[params.assets]
  favicon = "favicon.ico"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  pre = "<i class='fas fa-home'></i>&nbsp;"

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2
  pre = "<i class='fas fa-folder'></i>&nbsp;"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
  pre = "<i class='fas fa-heart'></i>&nbsp;"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
