baseURL = 'https://emad.blog/'
languageCode = 'en-us'
title = "Security Blog"
theme = 'hugo-PaperMod'


[params]
  # Load custom CSS that includes @font-face for Font Awesome
    customCSS = ["css/custom.css","extended/custom.css", "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"]
     ShowCodeCopyButtons = true


 # Social Icons (Modify with your actual links)
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/emadmohamed1/"

  [[params.socialIcons]]
    name = "x-twitter"
    url = "https://x.com/0xl33ch"
    

  enableStaticFileDeploy = true

[params.assets]
  favicon = "favicon.ico"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  pre = "<i class='fas fa-home'></i>&nbsp;"

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2
  pre = "<i class='fas fa-folder'></i>&nbsp;"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
  pre = "<i class='fas fa-heart'></i>&nbsp;"

[[menu.main]]
  name = "References"
  url = "/reference/"
  weight = 4
  pre = "<i class='fas fa-bookmark'></i>&nbsp;"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
